// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRYL2__5Vqj_ZJK6cmbYAn0vEa9iAReU',
    appId: '1:674636296496:web:c81805b598f76d828f18f5',
    messagingSenderId: '674636296496',
    projectId: 'taxi-59408',
    authDomain: 'taxi-59408.firebaseapp.com',
    storageBucket: 'taxi-59408.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xWmygHJWQ9f4S6W_nqZz99UuQfwzBOY',
    appId: '1:674636296496:android:b4bda05cdecea94d8f18f5',
    messagingSenderId: '674636296496',
    projectId: 'taxi-59408',
    storageBucket: 'taxi-59408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm4fJTsu6gSkdbAn1AWUlKwABNpnCHeOM',
    appId: '1:674636296496:ios:d876a0bf1555281f8f18f5',
    messagingSenderId: '674636296496',
    projectId: 'taxi-59408',
    storageBucket: 'taxi-59408.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm4fJTsu6gSkdbAn1AWUlKwABNpnCHeOM',
    appId: '1:674636296496:ios:d876a0bf1555281f8f18f5',
    messagingSenderId: '674636296496',
    projectId: 'taxi-59408',
    storageBucket: 'taxi-59408.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRYL2__5Vqj_ZJK6cmbYAn0vEa9iAReU',
    appId: '1:674636296496:web:fbaf93a185ad4ee88f18f5',
    messagingSenderId: '674636296496',
    projectId: 'taxi-59408',
    authDomain: 'taxi-59408.firebaseapp.com',
    storageBucket: 'taxi-59408.firebasestorage.app',
  );
}
